//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDropBoxClone.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFile", ReplyAction="http://tempuri.org/IService/AddFileResponse")]
        void AddFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddFile", ReplyAction="http://tempuri.org/IService/AddFileResponse")]
        System.Threading.Tasks.Task AddFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteFile", ReplyAction="http://tempuri.org/IService/DeleteFileResponse")]
        void DeleteFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteFile", ReplyAction="http://tempuri.org/IService/DeleteFileResponse")]
        System.Threading.Tasks.Task DeleteFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DownloadFile", ReplyAction="http://tempuri.org/IService/DownloadFileResponse")]
        void DownloadFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DownloadFile", ReplyAction="http://tempuri.org/IService/DownloadFileResponse")]
        System.Threading.Tasks.Task DownloadFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DBConnect", ReplyAction="http://tempuri.org/IService/DBConnectResponse")]
        void DBConnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DBConnect", ReplyAction="http://tempuri.org/IService/DBConnectResponse")]
        System.Threading.Tasks.Task DBConnectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ClientDropBoxClone.Service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ClientDropBoxClone.Service.IService>, ClientDropBoxClone.Service.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddFile() {
            base.Channel.AddFile();
        }
        
        public System.Threading.Tasks.Task AddFileAsync() {
            return base.Channel.AddFileAsync();
        }
        
        public void DeleteFile() {
            base.Channel.DeleteFile();
        }
        
        public System.Threading.Tasks.Task DeleteFileAsync() {
            return base.Channel.DeleteFileAsync();
        }
        
        public void DownloadFile() {
            base.Channel.DownloadFile();
        }
        
        public System.Threading.Tasks.Task DownloadFileAsync() {
            return base.Channel.DownloadFileAsync();
        }
        
        public void DBConnect() {
            base.Channel.DBConnect();
        }
        
        public System.Threading.Tasks.Task DBConnectAsync() {
            return base.Channel.DBConnectAsync();
        }
    }
}
